version: "3.8"

services:
  dogememes:
    build: 
      context: .
      dockerfile: Dockerfile.prod
      target: production
    ports:
      - "8001:4173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
