services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8002:4174"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4174/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
